version: "3.4"
services:
  klystron:
    image: klystron
    read_only: false
    entrypoint: sleep 999999
    build:
      network: host
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./klystron-data:/var/run/klystron:rw

  klystron-client:
    image: klystron
    depends_on:
      - klystron
    read_only: false
    build:
      network: host
      context: .
      dockerfile: Dockerfile
      target: dev
    command: '/var/run/klystron/examples/example.sh'
    volumes:
      - ./klystron-data/klystron.sock:/var/run/klystron/klystron.sock:rw
      - ./examples:/var/run/klystron/examples:rw

volumes:
  volatile:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "uid=1000,size=10M"
